/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "surface-container-highest": "#e2e2e2",
        "surface": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-container": "#757575",
        "on-background": "#1a1c1c",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed": "#e3e2e2",
        "on-primary-container": "#fffdff",
        "surface-container": "#eeeeee",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "primary": "#005dac",
        "primary-container": "#1976d2",
        "outline-variant": "#c1c6d4",
        "on-secondary-container": "#656464",
        "inverse-surface": "#2f3131",
        "outline": "#717783",
        "inverse-primary": "#a5c8ff",
        "on-surface": "#1a1c1c",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a5c8ff",
        "on-tertiary-fixed": "#1b1c1c",
        "secondary-fixed": "#e4e2e1",
        "secondary-fixed-dim": "#c8c6c6",
        "on-primary-fixed": "#001c3a",
        "on-tertiary-fixed-variant": "#464747",
        "surface-dim": "#dadada",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#414752",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d4e3ff",
        "on-secondary-fixed": "#1b1c1c",
        "secondary": "#5f5e5e",
        "secondary-container": "#e4e2e1",
        "surface-container-low": "#f3f3f3",
        "surface-tint": "#005faf",
        "on-tertiary-container": "#fffdfd",
        "background": "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "on-primary-fixed-variant": "#004786",
        "on-secondary-fixed-variant": "#474747",
        "inverse-on-surface": "#f1f1f1",
        "tertiary": "#5c5c5d"
      },
      spacing: {
        "gutter": "16px",
        "max-width": "1280px",
        "unit": "8px",
        "margin-desktop": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "date-stamp": ["Inter"],
        "title-lg": ["Inter"],
        "body-lg": ["Inter"],
        "h2": ["Inter"],
        "h1": ["Inter"],
        "label-sm": ["Inter"],
        "title-md": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "date-stamp": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "h2": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "h1": ["34px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "title-md": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
